#!/bin/sh

echo "Booting BusyBox initramfs..."

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "Mounting rootfs image..."

# 创建挂载点
mkdir /newroot

# 挂载镜像文件（假设内核已经把它作为 /dev/vda）
mount -t ext4 /dev/vda /newroot

if [ $? -ne 0 ]; then
    echo "Failed to mount rootfs!"
    exec sh
fi

echo "Switching to Alpine root..."

mount --move /proc /newroot/proc
mount --move /sys /newroot/sys
mount --move /dev /newroot/dev

exec switch_root /newroot /sbin/init
